name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: ( docker pull masterxilo/ubuntu-20-04-docker-compose || true ) && docker build . --file Dockerfile --tag masterxilo/ubuntu-20-04-docker-compose --cache-from masterxilo/ubuntu-20-04-docker-compose
    
    - name: Push the Docker image
      run: echo ${{ secrets.MASTERXILO_DOCKER_IO_PASSWORD }} | docker login --username masterxilo --password-stdin docker.io && docker push masterxilo/ubuntu-20-04-docker-compose && docker logout
